# RuboCop Configuration
#
# Code style and linting rules for the Rails backend.
# See https://docs.rubocop.org/rubocop/configuration.html

plugins:
  - rubocop-rails
  - rubocop-performance

require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

# Disable line ending checks (Windows/Unix compatibility)
Layout/EndOfLine:
  Enabled: false

# Disable Capybara cops (we don't use Capybara for API testing)
Capybara:
  Enabled: false

RSpec/Capybara:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false

FactoryBot:
  Enabled: false

# Layout
Layout/LineLength:
  Max: 120
  AllowedPatterns: ['^\s*#']
  Exclude:
    - 'db/seeds/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Metrics - relaxed for complex service classes
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'

Metrics/MethodLength:
  Max: 40
  Exclude:
    - 'db/migrate/**/*'
    - 'db/seeds/**/*'

Metrics/ClassLength:
  Max: 250

Metrics/AbcSize:
  Max: 50
  Exclude:
    - 'db/migrate/**/*'
    - 'db/seeds/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

# Style
Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

# Rails
Rails/FilePath:
  EnforcedStyle: arguments

Rails/SkipsModelValidations:
  Enabled: true
  AllowedMethods:
    - 'touch'
    - 'increment!'

Rails/I18nLocaleTexts:
  Enabled: false

# Naming - allow has_* predicate methods
Naming/PredicatePrefix:
  Enabled: false

# Lint - relax certain rules
Lint/NoReturnInBeginEndBlocks:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

# RSpec
RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'

RSpecRails:
  Enabled: true
